### ISSUE TITLE
 Unable to find a specification for `UIImageCropper'

### ISSUE THREAD

**Issue by xtremeactor** [jvk75/UIImageCropper#3]
Unable to find a specification for `UIImageCropper' is what I see when trying to install via CocoaPods.  What happened?

**Comment by jvk75** [comment]
Hi,
Try ```pod install --repo-update```
If I understood the question correctly your local pod repository is too old to find the package.

**Comment by jvk75** [comment]
Also if that doesn't help try reset the repo
```
pod repo remove master
pod setup
pod install
```
