### ISSUE TITLE
make square always

### ISSUE THREAD

**Issue by vre142** [jvk75/UIImageCropper#5]
Hi how can I set always square for cropping in this library?

**Comment by jvk75** [comment]
Hi,
 
Square can be done by setting the ratio to 1 (1/1). 
Either constructing the cropper 
```let cropper = UIImageCropper(cropRatio: 1)```
or setting variable ```cropper.cropRatio = 1```

**Comment by vre142** [comment]
Thanks for your reply can I do something for user to resize the square?

**Comment by jvk75** [comment]
Users can pinch to scale the image when cropping. 
Other than that resizing is out of the scope of the library.
